# Generated by Django 5.2.5 on 2026-02-16 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('iata_code', models.CharField(db_index=True, max_length=3, unique=True)),
                ('airport_name', models.CharField(max_length=200)),
                ('country', models.CharField(db_index=True, max_length=100)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('timezone', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'ordering': ['name', 'iata_code'],
                'indexes': [models.Index(fields=['name', 'country'], name='api_city_name_0c7dd7_idx'), models.Index(fields=['iata_code', 'is_active'], name='api_city_iata_co_d83724_idx')],
            },
        ),
    ]
