# Generated by Django 5.2.5 on 2026-02-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('stars', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Star'), (3, '3 Star'), (4, '4 Star'), (5, '5 Star')], default=3)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('review_count', models.IntegerField(default=0)),
                ('distance_from_center', models.DecimalField(decimal_places=2, help_text='Distance in kilometers', max_digits=6)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hotels',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name', 'location'], name='api_hotel_name_cff273_idx'), models.Index(fields=['stars', 'is_active'], name='api_hotel_stars_1364f8_idx'), models.Index(fields=['rating', 'is_active'], name='api_hotel_rating_eee5f0_idx')],
            },
        ),
    ]
