# Generated by Django 5.2.5 on 2026-02-16 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_hotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(help_text='e.g., Deluxe Room, Executive Suite', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price_per_night', models.DecimalField(decimal_places=2, help_text='Price in PKR', max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, help_text='Original price for discount display', max_digits=10, null=True)),
                ('available_rooms', models.IntegerField(default=0, help_text='Number of available rooms of this type')),
                ('max_guests', models.IntegerField(default=2, help_text='Maximum number of guests allowed')),
                ('room_image_url', models.URLField(blank=True, help_text='Optional room-specific image', max_length=500)),
                ('amenities', models.JSONField(blank=True, default=list, help_text='List of amenities as strings')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='api.hotel')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'ordering': ['price_per_night'],
                'indexes': [models.Index(fields=['hotel', 'is_active'], name='api_room_hotel_i_3ce8ca_idx'), models.Index(fields=['price_per_night'], name='api_room_price_p_e1415a_idx')],
            },
        ),
    ]
