# Generated by Django 5.2.5 on 2026-02-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(help_text='e.g., Toyota Camry, BMW 3 Series', max_length=100)),
                ('type', models.CharField(choices=[('compact', 'Compact'), ('mid-size', 'Mid-size'), ('suv', 'SUV'), ('luxury', 'Luxury'), ('electric', 'Electric'), ('convertible', 'Convertible'), ('truck', 'Truck'), ('van', 'Van')], help_text='Car type/category', max_length=20)),
                ('company', models.CharField(help_text='Rental company name', max_length=100)),
                ('price_per_day', models.DecimalField(decimal_places=2, help_text='Price per day in PKR', max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, help_text='Original price for discount display', max_digits=10, null=True)),
                ('car_image_url', models.URLField(blank=True, help_text='Car image URL', max_length=500)),
                ('transmission', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], default='automatic', max_length=10)),
                ('seats', models.IntegerField(default=5, help_text='Number of seats')),
                ('luggage_capacity', models.IntegerField(default=2, help_text='Luggage capacity in bags')),
                ('fuel_type', models.CharField(choices=[('gasoline', 'Gasoline'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid')], default='gasoline', max_length=20)),
                ('mileage', models.CharField(default='Unlimited', help_text='Mileage allowance', max_length=50)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, help_text='Average customer rating', max_digits=3, null=True)),
                ('review_count', models.IntegerField(default=0, help_text='Number of customer reviews')),
                ('features', models.JSONField(blank=True, default=list, help_text='List of features as strings')),
                ('is_available', models.BooleanField(default=True, help_text='Is the car currently available for rent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
                'ordering': ['price_per_day'],
                'indexes': [models.Index(fields=['type', 'is_available'], name='api_car_type_639a1e_idx'), models.Index(fields=['price_per_day'], name='api_car_price_p_29c7ba_idx'), models.Index(fields=['company', 'is_available'], name='api_car_company_3f0a6a_idx')],
            },
        ),
    ]
