# Generated by Django 5.2.5 on 2026-02-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Package title/name', max_length=200)),
                ('destination', models.CharField(help_text='Destination city and country', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed package description')),
                ('hotel_name', models.CharField(help_text='Hotel name', max_length=200)),
                ('hotel_location', models.CharField(help_text='Hotel location/address', max_length=200)),
                ('hotel_stars', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Star'), (3, '3 Star'), (4, '4 Star'), (5, '5 Star')], default=3)),
                ('hotel_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('hotel_review_count', models.IntegerField(default=0)),
                ('hotel_image_url', models.URLField(blank=True, help_text='Hotel image URL', max_length=500)),
                ('airline', models.CharField(help_text='Airline name', max_length=100)),
                ('departure_airport', models.CharField(help_text='Departure airport code', max_length=10)),
                ('arrival_airport', models.CharField(help_text='Arrival airport code', max_length=10)),
                ('flight_duration', models.CharField(help_text='Flight duration (e.g., 7h 15m)', max_length=20)),
                ('flight_stops', models.IntegerField(default=0, help_text='Number of stops')),
                ('departure_time', models.CharField(help_text='Departure time (e.g., 08:30)', max_length=10)),
                ('arrival_time', models.CharField(help_text='Arrival time (e.g., 21:45)', max_length=10)),
                ('price_per_person', models.DecimalField(decimal_places=2, help_text='Price per person in PKR', max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, help_text='Original price for discount display', max_digits=10, null=True)),
                ('price_per_package', models.DecimalField(blank=True, decimal_places=2, help_text='Total package price in PKR', max_digits=10, null=True)),
                ('nights', models.IntegerField(default=1, help_text='Number of nights')),
                ('package_type', models.CharField(choices=[('city', 'City Break'), ('beach', 'Beach'), ('adventure', 'Adventure'), ('luxury', 'Luxury'), ('romantic', 'Romantic'), ('family', 'Family'), ('cultural', 'Cultural'), ('wellness', 'Wellness')], help_text='Package category', max_length=20)),
                ('highlights', models.JSONField(blank=True, default=list, help_text='List of highlight tags as strings')),
                ('includes', models.JSONField(blank=True, default=list, help_text='List of included items as strings')),
                ('availability', models.IntegerField(default=0, help_text='Number of available slots')),
                ('bookings', models.IntegerField(default=0, help_text='Number of bookings made')),
                ('is_featured', models.BooleanField(default=False, help_text='Is this a featured package?')),
                ('is_popular', models.BooleanField(default=False, help_text='Is this a popular package?')),
                ('is_active', models.BooleanField(default=True, help_text='Is the package currently active?')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['destination', 'is_active'], name='api_package_destina_abcb3a_idx'), models.Index(fields=['package_type', 'is_active'], name='api_package_package_c1deb9_idx'), models.Index(fields=['price_per_person'], name='api_package_price_p_89ce4d_idx'), models.Index(fields=['status'], name='api_package_status_9c474c_idx')],
            },
        ),
    ]
