# Generated by Django 5.2.5 on 2026-02-24 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_package'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('chat', 'AI Chat'), ('itinerary', 'Itinerary')], default='chat', max_length=20)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_activity_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=16)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.chatsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('data', models.JSONField(help_text='Itinerary payload returned to the frontend.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_itineraries', to='api.chatsession')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_itineraries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('destination', models.CharField(blank=True, help_text='Destination this document is about (e.g. Islamabad, Pakistan)', max_length=200)),
                ('category', models.CharField(choices=[('guide', 'Travel Guide'), ('tip', 'Travel Tip'), ('safety', 'Safety'), ('weather', 'Weather'), ('transport', 'Transport'), ('general', 'General')], default='general', max_length=32)),
                ('content', models.TextField(help_text='Plain text content used for RAG context.')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(blank=True, help_text='Short source label (e.g. internal_guide, blog, faq).', max_length=100)),
                ('embedding', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['destination', 'category'], name='api_knowled_destina_ba38e1_idx'), models.Index(fields=['is_active'], name='api_knowled_is_acti_f59105_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['user', 'session_type'], name='api_chatses_user_id_7ea247_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['is_active', 'session_type'], name='api_chatses_is_acti_1bb185_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session', 'created_at'], name='api_chatmes_session_2462c9_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['sender'], name='api_chatmes_sender_514a19_idx'),
        ),
        migrations.AddIndex(
            model_name='generateditinerary',
            index=models.Index(fields=['user'], name='api_generat_user_id_5ceb37_idx'),
        ),
        migrations.AddIndex(
            model_name='generateditinerary',
            index=models.Index(fields=['session'], name='api_generat_session_cba0aa_idx'),
        ),
    ]
