# Generated by Django 5.2.5 on 2026-04-26 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_bookingcart_bookingitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('images', models.JSONField(blank=True, default=list, help_text='List of image URLs')),
                ('likes_count', models.IntegerField(default=0)),
                ('comments_count', models.IntegerField(default=0)),
                ('shares_count', models.IntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Community Post',
                'verbose_name_plural': 'Community Posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityPostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name='bookingitem',
            new_name='api_booking_cart_id_f4ad4b_idx',
            old_name='api_bookingi_cart_id_7e8ca2_idx',
        ),
        migrations.RenameIndex(
            model_name='bookingitem',
            new_name='api_booking_referen_43dec2_idx',
            old_name='api_bookingi_referen_9f99af_idx',
        ),
        migrations.AddField(
            model_name='communitypost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communitypostlike',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='api.communitypost'),
        ),
        migrations.AddField(
            model_name='communitypostlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='communitypost',
            index=models.Index(fields=['user', 'created_at'], name='api_communi_user_id_5c41dc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='communitypostlike',
            unique_together={('user', 'post')},
        ),
    ]
