# Generated by Django 6.0.5 on 2026-05-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_bookingitem_cart_booking_bookingitem_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingitem',
            name='item_type',
            field=models.CharField(choices=[('hotel_room', 'Hotel Room'), ('flight', 'Flight'), ('car', 'Car'), ('package', 'Package')], max_length=20),
        ),
    ]
