# Generated by Django 6.0.5 on 2026-05-18 17:03

from django.db import migrations, models


def copy_existing_images(apps, schema_editor):
    Hotel = apps.get_model('api', 'Hotel')
    Room = apps.get_model('api', 'Room')
    Car = apps.get_model('api', 'Car')
    Package = apps.get_model('api', 'Package')

    for hotel in Hotel.objects.all():
        hotel.image = getattr(hotel, 'image_url', '') or ''
        hotel.save(update_fields=['image'])

    for room in Room.objects.all():
        room.room_image = getattr(room, 'room_image_url', '') or ''
        room.save(update_fields=['room_image'])

    for car in Car.objects.all():
        car.car_image = getattr(car, 'car_image_url', '') or ''
        car.save(update_fields=['car_image'])

    for package in Package.objects.all():
        package.hotel_image = getattr(package, 'hotel_image_url', '') or ''
        package.save(update_fields=['hotel_image'])


def reverse_copy_existing_images(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_bookingitem_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='hotel_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='room_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.RunPython(copy_existing_images, reverse_copy_existing_images),
    ]
