# Generated by Django 6.0.5 on 2026-05-18 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_car_car_image_hotel_image_package_hotel_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='car_image_url',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='package',
            name='hotel_image_url',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_image_url',
        ),
    ]
